name: Uptime Check One
run-name: Uptime Check One ${{ github.actor }}
on:
  workflow_dispatch
  
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: curl http://www.google.it
